export enum Alliance {
    Chaos = 'Chaos',
    Imperial = 'Imperial',
    Xenos = 'Xenos',
}

export enum Faction {
    Ultramarines = 'Ultramarines',
    Black_Legion = 'Black Legion',
    Orks = 'Orks',
    ADEPTA_SORORITAS = 'ADEPTA SORORITAS',
    Necrons = 'Necrons',
    Astra_militarum = 'Astra militarum',
    Death_Guard = 'Death guard',
    Black_Templars = 'Black templars',
    Aeldari = 'Aeldari',
    Space_Wolves = 'Space Wolves',
    T_Au = 'T\'au Empire',
    Dark_Angels = 'Dark Angels',
    Thousand_Sons = 'Thousand Sons',
    Tyranids = 'Tyranids',
}

export enum Rarity {
    Common = 'Common',
    Epic = 'Epic',
    Legendary = 'Legendary',
    Rare = 'Rare',
    Uncommon = 'Uncommon',
}

export enum TraitTypeRaw {
    Psyker = 'Psyker',
    Overwatch = 'Overwatch',
    HeavyWeapon = 'Heavy Weapon',
    Infiltrate = 'Infiltrate',
    Flying = 'Flying',
    MKXGravis = 'MK X Gravis',
    Healer = 'Healer',
    FinalVengeance = 'Final Vengeance',
    LetTheGalaxyBurn = 'Let the Galaxy Burn',
    DeepStrike = 'Deep Strike',
    TerminatorArmour = 'Terminator Armour',
    Resilient = 'Resilient',
    BeastSnagga = 'Beast Snagga',
    Mechanic = 'Mechanic',
    Mechanical = 'Mechanical',
    Explodes = 'Explodes',
    Dakka = 'Dakka',
    Mounted = 'Mounted',
    ActOfFaith = 'Act of Faith',
    LivingMetal = 'Living Metal',
    IndirectFire = 'Indirect Fire',
    ContagionsOfNurgle = 'Contagions of Nurgle',
    PutridExplosion = 'Putrid Explosion',
    Parry = 'Parry',
    Terrifying = 'Terrifying',
    Unstoppable = 'Unstoppable',
    CloseCombatWeakness = 'Close Combat Weakness',
    Camouflage = 'Camouflage',
    WeaverOfFates = 'Weaver of Fates',
    BigTarget = 'Big Target',
    ShadowInTheWarp = 'Shadow in the Warp',
    Synapse = 'Synapse'
}

export enum Traits {
    None = 0,
    Psyker = 1 << 0,
    Overwatch = 1 << 1,
    HeavyWeapon = 1 << 2,
    Infiltrate = 1 << 3,
    Flying = 1 << 4,
    MKXGravis = 1 << 5,
    Healer = 1 << 6,
    FinalVengeance = 1 << 7,
    LetTheGalaxyBurn = 1 << 8,
    DeepStrike = 1 << 9,
    TerminatorArmour = 1 << 10,
    Resilient = 1 << 11,
    BeastSnagga = 1 << 12,
    Mechanic = 1 << 13,
    Mechanical = 1 << 14,
    Explodes = 1 << 15,
    Dakka = 1 << 16,
    Mounted = 1 << 17,
    ActOfFaith = 1 << 18,
    LivingMetal = 1 << 19,
    IndirectFire = 1 << 20,
    ContagionsOfNurgle = 1 << 21,
    PutridExplosion = 1 << 22,
    Parry = 1 << 23,
    Terrifying = 1 << 24,
    Unstoppable = 1 << 25,
    CloseCombatWeakness = 1 << 26,
    Camouflage = 1 << 27,
    WeaverOfFates = 1 << 28,
    BigTarget = 1 << 29,
    ShadowInTheWarp = 1 << 30,
    Synapse = 1 << 31,
}

export enum DamageTypeRaw {
    Physical = 'Physical',
    Psychic = 'Psychic',
    Bolter = 'Bolter',
    Piercing = 'Piercing',
    Power = 'Power',
    HeavyRound = 'Heavy Round',
    Chain = 'Chain',
    Projectile = 'Projectile',
    Flame = 'Flame',
    Molecular = 'Molecular',
    Particle = 'Particle',
    Plasma = 'Plasma',
    Energy = 'Energy',
    Las = 'Las',
    Blast = 'Blast',
    Direct = 'Direct',
    Pulse = 'Pulse',
    Melta = 'Melta',
}

export enum DamageTypes {
    None = 0,
    Physical = 1 << 0,
    Psychic = 1 << 1,
    Bolter = 1 << 2,
    Piercing = 1 << 3,
    Power = 1 << 4,
    HeavyRound = 1 << 5,
    Chain = 1 << 6,
    Projectile = 1 << 7,
    Flame = 1 << 8,
    Molecular = 1 << 10,
    Particle = 1 << 11,
    Plasma = 1 << 12,
    Energy = 1 << 13,
    Las = 1 << 14,
    Blast = 1 << 15,
    Direct = 1 << 16,
    Pulse = 1 << 17,
    Melta = 1 << 18,
}