export enum DamageType {
    Bio = 'Bio',
    Blast = 'Blast',
    Bolter = 'Bolter',
    Chain = 'Chain',
    Direct = 'Direct',
    Energy = 'Energy',
    Eviscerate = 'Eviscerate',
    Flame = 'Flame',
    HeavyRound = 'Heavy Round',
    Las = 'Las',
    Melta = 'Melta',
    Molecular = 'Molecular',
    Particle = 'Particle',
    Physical = 'Physical',
    Piercing = 'Piercing',
    Plasma = 'Plasma',
    Power = 'Power',
    Projectile = 'Projectile',
    Psychic = 'Psychic',
    Pulse = 'Pulse',
    Toxic = 'Toxic',
}
