export enum Faction {
    Ultramarines = 'Ultramarines',
    Black_Legion = 'Black Legion',
    Orks = 'Orks',
    ADEPTA_SORORITAS = 'Adepta Sororitas',
    Necrons = 'Necrons',
    Astra_militarum = 'Astra Militarum',
    Death_Guard = 'Death Guard',
    Black_Templars = 'Black Templars',
    Aeldari = 'Aeldari',
    Space_Wolves = 'Space Wolves',
    T_Au = "T'au Empire",
    Dark_Angels = 'Dark Angels',
    Thousand_Sons = 'Thousand Sons',
    Tyranids = 'Tyranids',
    AdeptusMechanicus = 'Adeptus Mechanicus',
    WorldEaters = 'World Eaters',
    BloodAngels = 'Blood Angels',
    GenestealerCults = 'Genestealer Cults',
    AdeptusCustodes = 'Adeptus Custodes',
    EmperorsChildren = "Emperor's Children",
    LeaguesOfVotann = 'Leagues of Votann',
}
