export enum RarityStars {
    None,
    OneStar,
    TwoStars,
    ThreeStars,
    FourStars,
    FiveStars,
    RedOneStar,
    RedTwoStars,
    RedThreeStars,
    RedFourStars,
    RedFiveStars,
    OneBlueStar,
    TwoBlueStars,
    ThreeBlueStars,
    MythicWings,
}
