import {
    arsenalOfWar,
    conflictOperations,
    defeatWaves,
    defeatWaves2,
    factionBoostAdeptusMechanicus,
    factionBoostDarkAngels,
    factionBoostSpaceWolves,
    factionFocus,
    forTheDarkGods,
    forTheEmperor,
    globalHse11thEditionWeek1BloodAngels,
    globalHse11thEditionWeek1Orks,
    globalHse11thEditionWeek2BloodAngels,
    globalHse11thEditionWeek2Orks,
    globalHse11thEditionWeek3BloodAngels,
    globalHse11thEditionWeek3Orks,
    hse11thEditionWeek1,
    hse11thEditionWeek2,
    hse11thEditionWeek3,
    hseTraitBoostRapidAssault,
    hseTraitBoostTerminatorArmour,
    killTyranids,
    machineHunt,
    rarityTrainingRush,
    squigSmash,
    traitBoostFlying,
    traitBoostPsyker,
    warpSurge,
} from './data';
import type { HomescreenEventData } from './homescreen-event.model';

const rawHomescreenEvents = [
    arsenalOfWar,
    conflictOperations,
    defeatWaves2,
    defeatWaves,
    factionBoostAdeptusMechanicus,
    factionBoostDarkAngels,
    factionBoostSpaceWolves,
    factionFocus,
    forTheDarkGods,
    forTheEmperor,
    globalHse11thEditionWeek1BloodAngels,
    globalHse11thEditionWeek1Orks,
    globalHse11thEditionWeek2BloodAngels,
    globalHse11thEditionWeek2Orks,
    globalHse11thEditionWeek3BloodAngels,
    globalHse11thEditionWeek3Orks,
    hse11thEditionWeek1,
    hse11thEditionWeek2,
    hse11thEditionWeek3,
    hseTraitBoostRapidAssault,
    hseTraitBoostTerminatorArmour,
    killTyranids,
    machineHunt,
    rarityTrainingRush,
    squigSmash,
    traitBoostFlying,
    traitBoostPsyker,
    warpSurge,
];

export const homescreenEvents = rawHomescreenEvents as unknown as HomescreenEventData[];
