/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/guild': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the guild data for the authenticated user, fetched live from the Tacticus API using the user's stored guild API key. */
        get: operations['getGuild'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/raid/seasons': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all known seasons for this guild with their aggregation status. Seasons in the 11-season window that have not yet been fetched appear as NotAggregated. Old seasons only appear if already persisted. */
        get: operations['getGuildRaidSeasons'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/raid/{season}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current season's raw Tacticus API response, or a persisted aggregated summary for a historical season. */
        get: operations['getGuildRaidSeason'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/history': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DEPRECATED. Returns the legacy roster snapshot list (GuildData.RosterData blob) plus sequenceNumber. Used by the old save-snapshot flow. Replace with GET /guild/roster/snapshots, which now includes sequenceNumber and the per-snapshot memberIds needed for the new diff UI. Will be removed once the CUT-AWAY write path is dropped.
         * @deprecated
         */
        get: operations['getGuildRosterHistory'];
        /** Saves a new roster snapshot. Always returns 200 — check status field for 'OK' vs 'TIMED_OUT' (30-second hard limit). Response includes per-phase timing for diagnostics. sequenceNumber in the request body is accepted but ignored. */
        put: operations['putGuildRosterHistory'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/member': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns live unit roster for a single guild member, resolved via PlayerOverrides or PlayerGuildData. */
        get: operations['getGuildRosterMember'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/snapshots': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists snapshot metadata with per-snapshot player ID lists and current-roster members. One call drives the entire diff-UI from/to/player picker — no subsequent calls needed until the leader selects a player. */
        get: operations['getGuildRosterSnapshots'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/snapshot/{snapshotId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns snapshot metadata only (id, name, createdAt). Character data is no longer returned here — use GET /guild/roster/player-chain?userId={id} instead. */
        get: operations['getGuildRosterSnapshot'];
        put?: never;
        post?: never;
        /** Deletes a roster snapshot by its ID, including all GuildSnapshotPlayerIndex entries and removes the entry from each player's GuildPlayerRosterChain. */
        delete: operations['deleteGuildRosterSnapshot'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/player-chain': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the full per-player delta chain for a single guild member, oldest entry first. The base entry (index 0) contains the player's full character list; each subsequent entry is a delta relative to the previous. Call this once after the leader selects a player in the diff UI — the client applies the chain client-side to reconstruct state at any two snapshots. */
        get: operations['getGuildRosterPlayerChain'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/migrate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One-time idempotent migration. Reads existing GuildRosterSnapshot.Members blobs and populates GuildSnapshotPlayerIndex and GuildPlayerRosterChain for any snapshot not yet migrated. Safe to call multiple times. The leader should trigger this once from the roster snapshots page. */
        post: operations['postGuildRosterMigrate'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/raid/performance-index': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns per-player performance-index scalars for every aggregated historical season. */
        get: operations['GetGuildPerformanceIndex'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/sharedLeaderboards': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns combined cross-guild leaderboards for the requesting guild and any guilds listing this guild's tag in CombinedGuildTags. Guild API key holders only. */
        get: operations['getSharedLeaderboards'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/member/raid/performance-index': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the calling member's own performance-index scalar for every aggregated historical season. */
        get: operations['getMemberGuildPerformanceIndex'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/member/raid': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns an anonymized aggregated summary of the current raid season for the calling member. Always GuildSeasonSummary shape (never raw). Non-self playerIds become 'Anonymous'; comps are preserved. */
        get: operations['getMemberGuildRaidCurrentSeason'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/member/raid/{season}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns an anonymized aggregated raid season summary for the calling member. Always GuildSeasonSummary shape (never raw). Non-self playerIds become 'Anonymous'; comps are preserved. Members may trigger backfill for historical seasons. */
        get: operations['getMemberGuildRaidSeason'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/users/tacticusApiKey': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stores or updates the authenticated user's Tacticus API keys and sharing preferences. */
        put: operations['updateTacticusApiKey'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/member/sharedLeaderboards': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns combined cross-guild leaderboards for the member's guild. Requires ShareGuildMemberPerformance and confirmed Tacticus membership. */
        get: operations['getMemberSharedLeaderboards'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/raid/token_usage': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns per-season token and bomb counts for all guild members across all aggregated historical seasons. Triggers backfill if needed. */
        get: operations['getGuildTokenUsage'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/member/token_usage': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the calling member's own per-season token and bomb counts across all aggregated historical seasons. */
        get: operations['getMemberGuildTokenUsage'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetTacticusApiKeyRequest: {
            /** @description Personal Tacticus API key. Omit or send empty to clear. */
            apiKey?: string;
            /** @description Guild API key. Omit or send empty to clear. */
            guildApiKey?: string;
            /** @description Player's Tacticus user ID. Omit or send empty to clear. */
            tacticusUserId?: string;
            /** @description 5-character uppercase alphanumeric guild tag. Ignored when guildApiKey is provided (tag is fetched from the Tacticus API instead). */
            guildTag?: string;
            shareInGameNameWithGuild?: boolean;
            shareRosterDataWithGuild?: boolean;
            shareGuildMemberPerformance?: boolean;
            /** @description Tags of other guilds whose raid data should be merged into shared leaderboards. **Absent** (field omitted) = leave existing tags unchanged. **Empty array** (`[]`) = clear all combined tags. **Non-empty array** = replace combined tags with the supplied list. Only meaningful when the user holds a guild API key. */
            combinedGuildTags?: string[];
        };
        /** @enum {string} */
        GuildRole: 'MEMBER' | 'OFFICER' | 'CO_LEADER' | 'LEADER';
        GuildMember: {
            /** Format: uuid */
            userId: string;
            role: components['schemas']['GuildRole'];
            level: number;
            /** Format: int64 */
            lastActivityOn?: number | null;
        };
        Guild: {
            /** Format: uuid */
            guildId: string;
            guildTag: string;
            name: string;
            level: number;
            members: components['schemas']['GuildMember'][];
            guildRaidSeasons: number[];
        };
        GuildResponse: {
            guild: components['schemas']['Guild'];
        };
        GuildApiError: {
            code: string;
            message: string;
            data?: unknown;
        };
        /**
         * @description 0=Found, 1=NotFound, 2=Empty, 3=TransientError, 4=TooOld (out of 11-season window and not in DB), 5=NotAggregated (in window but not yet fetched)
         * @enum {integer}
         */
        SeasonFetchStatus: 0 | 1 | 2 | 3 | 4 | 5;
        GuildRaidSeasonsResponse: {
            currentSeason?: number | null;
            guildTag: string;
            seasons: components['schemas']['GuildSeasonEntry'][];
        };
        GuildSeasonEntry: {
            season: number;
            status: components['schemas']['SeasonFetchStatus'];
            /** Format: date-time */
            aggregatedAt?: string | null;
        };
        /** @description Returned when the requested season equals the current season. Contains the raw Tacticus API payload. */
        CurrentSeasonRaidResponse: {
            season: number;
            raidResponse: {
                [key: string]: unknown;
            };
        };
        /** @description Returned for a historical season that has been aggregated and persisted. */
        HistoricalSeasonResponse: {
            season: number;
            status: components['schemas']['SeasonFetchStatus'];
            summary?: components['schemas']['GuildSeasonSummary'];
            /** Format: date-time */
            aggregatedAt?: string;
        };
        EnemyInfo: {
            enemyId: string;
            rarity: string;
            /** @description 0=boss, 1=left prime, 2=right prime */
            encounterIndex: number;
            maxHp: number;
            set: number;
        };
        GuildSeasonSummary: {
            version: number;
            season: number;
            /**
             * Format: int64
             * @description Total damage across all rarities, tokens and bombs
             */
            totalDamage: number;
            damageSummary: components['schemas']['GuildDamageSeasonSummary'];
            /** @description Top-5 single hits per boss/prime, top-2 rarities only */
            leaderboards: components['schemas']['GuildSeasonBossLeaderboard'][];
            /** @description Per-loop per-boss token counts, all rarities */
            loops: components['schemas']['GuildSeasonLoopInfo'][];
            /** @description Per-player hit-vs-guild ratios, top-2 rarities, bosses only */
            performanceIndex: components['schemas']['GuildSeasonPerformanceIndexEntry'][];
            /** @description Raw per-player hit arrays plus guild aggregates, top-2 rarities */
            bossPerformance: components['schemas']['GuildSeasonBossPerformanceEntry'][];
        };
        GuildDamageSeasonSummary: {
            textData: components['schemas']['GuildDamageSeasonSummaryTextData'];
            guildEntries: components['schemas']['GuildDamageSeasonSummaryGuildBossEntry'][];
            playerEntries: components['schemas']['GuildDamageSeasonSummaryPlayerBossEntry'][];
        };
        GuildDamageSeasonSummaryTextData: {
            playerData: components['schemas']['GuildDamageSeasonSummaryTextPlayerData'][];
        };
        GuildDamageSeasonSummaryTextPlayerData: {
            /** @description Null when anonymized */
            playerId?: string | null;
            tokens: number;
            bombs: number;
            primeHits: number;
            bossKillHits: number;
            /** Format: int64 */
            maxDamage: number;
            /** Format: int64 */
            totalDamage: number;
            maxDamageTarget?: components['schemas']['EnemyInfo'];
        };
        GuildDamageSeasonSummaryGuildBossEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            /** Format: double */
            averageDamage: number;
            /** Format: double */
            averageDamageWithoutKills: number;
            /** Format: int64 */
            maxDamage: number;
            /** Format: int64 */
            maxDamageWithoutKills?: number | null;
            maxDamagePlayerId?: string | null;
            maxDamageWithoutKillsPlayerId?: string | null;
            maxDamageComp?: string[] | null;
            maxDamageWithoutKillsComp?: string[] | null;
        };
        GuildDamageSeasonSummaryPlayerBossEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            /** @description Null when anonymized */
            playerId?: string | null;
            /** Format: double */
            averageDamage: number;
            /** Format: double */
            averageDamageWithoutKills: number;
            /** Format: int64 */
            maxDamage: number;
            /** Format: int64 */
            maxDamageWithoutKills?: number | null;
            maxDamageComp?: string[] | null;
            maxDamageWithoutKillsComp?: string[] | null;
        };
        GuildSeasonBossLeaderboard: {
            enemyInfo: components['schemas']['EnemyInfo'];
            entries: components['schemas']['GuildSeasonBossLeaderboardEntry'][];
        };
        GuildSeasonBossLeaderboardEntry: {
            /** Format: int64 */
            damage: number;
            guildTag?: string | null;
            isOwnGuild?: boolean | null;
            /** @description Null when anonymized */
            playerId?: string | null;
            /** @description Null when anonymized */
            comp?: string[] | null;
        };
        GuildSeasonLoopInfo: {
            loopNumber: number;
            enemyInfo: components['schemas']['EnemyInfo'];
            bossTokens: number;
            leftPrimeTokens: number;
            rightPrimeTokens: number;
        };
        GuildSeasonPerformanceIndexEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            playerEntries: components['schemas']['GuildSeasonPerformanceIndexPlayerEntry'][];
        };
        GuildSeasonPerformanceIndexPlayerEntry: {
            /** @description Null when anonymized */
            playerId?: string | null;
            /**
             * Format: double
             * @description Player avg / guild avg including kills. 1.5 = +50%.
             */
            performanceIndex: number;
            /** Format: double */
            performanceIndexWithoutKills: number;
        };
        GuildSeasonBossPerformanceEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            /** Format: double */
            guildAverageDamage: number;
            /** Format: double */
            guildAverageDamageWithoutKills: number;
            /** Format: int64 */
            guildMaxDamage: number;
            /** Format: int64 */
            guildMaxDamageWithoutKills: number;
            playerEntries: components['schemas']['GuildSeasonPlayerPerformanceEntry'][];
        };
        GuildSeasonPlayerPerformanceEntry: {
            /** @description Null when anonymized */
            playerId?: string | null;
            nonKillHits: number[];
            killHits: number[];
        };
        GuildRosterSnapshotsResponse: {
            snapshots: components['schemas']['RosterSnapshotInfo'][];
            atCapacity: boolean;
            maxSnapshots: number;
            /** @description Guild members who currently have a shared API key (via PlayerGuildData opt-in or PlayerOverrides). These are the players selectable when 'current rosters' is the 'to' point. */
            currentRosterMembers: components['schemas']['CurrentRosterMember'][];
            /** @description Current RosterSequenceNumber from GuildData. Must be sent back unmodified as sequenceNumber in PUT /guild/roster/history when saving a new snapshot. */
            sequenceNumber: number;
        };
        RosterSnapshotInfo: {
            /** Format: uuid */
            snapshotId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** @description User IDs of players who have a chain entry for this snapshot. Populated from GuildSnapshotPlayerIndex — no character data read. */
            memberIds: string[];
        };
        CurrentRosterMember: {
            userId: string;
            playerName: string;
        };
        /** @description Snapshot metadata only. Character data is accessed via GET /guild/roster/player-chain. */
        RosterSnapshotMeta: {
            /** Format: uuid */
            snapshotId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Core userId plus any extra properties stored via JsonExtensionData (delta fields vary by client implementation). */
        RosterSnapshotMember: {
            userId: string;
        } & {
            [key: string]: unknown;
        };
        /** @description One entry in a player's delta chain. Index 0 is the base (full character list); subsequent entries are deltas relative to the previous entry. SnapshotId/name/createdAt mirror the parent GuildRosterSnapshot row. */
        PlayerRosterChainEntry: {
            /** Format: uuid */
            snapshotId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            memberData?: components['schemas']['RosterSnapshotMember'];
        };
        PlayerRosterChainResponse: {
            userId: string;
            /** @description Chain entries in chronological order (oldest/base first). Empty array if no snapshots exist for this player. */
            chain: components['schemas']['PlayerRosterChainEntry'][];
        };
        SeasonPlayerPerformanceIndex: {
            /** @description Null when the caller is a keyless member (only their own entry is returned). */
            playerId?: string | null;
            /**
             * Format: double
             * @description Player avg non-kill boss damage / guild avg. 1.5 = +50% above guild mean.
             */
            performanceIndex?: number;
        };
        SeasonPerformanceIndexData: {
            season?: number;
            playerEntries?: components['schemas']['SeasonPlayerPerformanceIndex'][];
        };
        GuildPerformanceIndexResponse: {
            guildTag?: string;
            /** @description One entry per season with stored performance-index data, newest first. */
            entries?: components['schemas']['SeasonPerformanceIndexData'][];
        };
        SharedLeaderboardsResponse: {
            season: number;
            /** @description Combined boss leaderboard entries across all participating guilds. Player IDs are replaced with guild display names. */
            leaderboards: components['schemas']['GuildSeasonBossLeaderboard'][];
            /** @description Diagnostic timing data (milliseconds per phase) */
            timing?: {
                [key: string]: number;
            };
        };
        PlayerTokenUsage: {
            /** @description Tacticus user ID (GUID string) */
            userId?: string;
            /** @description Total Battle-type hits (prime hits + boss hits + killing blows) */
            tokens?: number;
            /** @description Total Bomb-type hits */
            bombs?: number;
        };
        SeasonTokenUsage: {
            season?: number;
            players?: components['schemas']['PlayerTokenUsage'][];
        };
        GuildTokenUsageResponse: {
            guildTag?: string;
            /** @description One entry per aggregated season, newest first. For the member endpoint, each season's players list is filtered to the requesting member only. */
            seasons?: components['schemas']['SeasonTokenUsage'][];
        };
        /** @description Wall-clock durations (milliseconds) for each I/O phase of the request. All values are end-to-end wall time inclusive of connection-pool wait, network RTT, query execution, and EF materialization. */
        GuildRosterMemberTimings: {
            /** @description Total handler wall time. */
            totalMs: number;
            /** @description GuildRequestHelper.GetGuildAsync — JWT validation, SQL user-row lookup, and Tacticus guild API call (skipped on cache hit). */
            getGuildMs: number;
            /** @description SQL query for the GuildData row (used to resolve PlayerOverrides). */
            sqlGuildDataMs: number;
            /** @description SQL query for the PlayerGuildData row. Null when the override path was taken instead. */
            sqlPlayerDataMs?: number | null;
            /** @description Tacticus API call to fetch the player's live unit roster. */
            tacticusPlayerApiMs: number;
        };
        GuildRosterMemberResponse: {
            /**
             * @description How the member's API key was resolved: 'override' = via PlayerOverrides on GuildData, 'tacticusApi' = via PlayerGuildData opt-in.
             * @enum {string}
             */
            source: 'override' | 'tacticusApi';
            playerName: string;
            /** @description Live unit roster as returned by the Tacticus API. */
            units: Record<string, never>[];
            timings: components['schemas']['GuildRosterMemberTimings'];
        };
    };
    responses: {
        /** @description Missing or invalid JWT */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['GuildApiError'];
            };
        };
        /** @description Not found, permission denied, or other application error */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['GuildApiError'];
            };
        };
        /** @description Upstream Tacticus API call failed */
        TacticusApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['GuildApiError'];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildResponse'];
                };
            };
            400: components['responses']['TacticusApiError'];
            401: components['responses']['Unauthorized'];
            /** @description No guild API key stored for the user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGuildRaidSeasons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildRaidSeasonsResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRaidSeason: {
        parameters: {
            query?: {
                /** @description Unix epoch milliseconds. Any persisted row with aggregatedAt before this timestamp is re-fetched and re-aggregated. */
                forceRefreshAfter?: number;
            };
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current-season raw response or historical aggregated summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json':
                        | components['schemas']['CurrentSeasonRaidResponse']
                        | components['schemas']['HistoricalSeasonResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRosterHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        sequenceNumber: number;
                        snapshots: components['schemas']['RosterSnapshotMember'][];
                    };
                };
            };
            401: components['responses']['Unauthorized'];
            502: components['responses']['TacticusApiError'];
        };
    };
    putGuildRosterHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    /** @description Ignored. Retained for backwards compatibility; may be omitted. */
                    sequenceNumber?: number;
                    snapshot: {
                        name: string;
                        members: components['schemas']['RosterSnapshotMember'][];
                    };
                };
            };
        };
        responses: {
            /** @description Always returned (even on timeout — check status field). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /**
                         * @description 'OK' means the snapshot was saved. 'TIMED_OUT' means the operation exceeded 30 seconds and was aborted — the snapshot was NOT saved.
                         * @enum {string}
                         */
                        status: 'OK' | 'TIMED_OUT';
                        /**
                         * Format: uuid
                         * @description ID of the newly created snapshot. Present only when status is 'OK'.
                         */
                        snapshotId?: string;
                        /** @description Per-phase durations for diagnostics. Phases: getGuild, parseBody, countCheck, nameCheck, chainLoad, chainProcess, saveChanges. On TIMED_OUT only completed phases appear. */
                        timings: {
                            phase: string;
                            ms: number;
                        }[];
                        /** @description Total elapsed milliseconds at response time. */
                        totalMs: number;
                    };
                };
            };
            400: components['responses']['ApiError'];
            401: components['responses']['Unauthorized'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRosterMember: {
        parameters: {
            query: {
                /** @description Tacticus user ID of the guild member to fetch. */
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildRosterMemberResponse'];
                };
            };
            400: components['responses']['ApiError'];
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRosterSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildRosterSnapshotsResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRosterSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['RosterSnapshotMeta'];
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    deleteGuildRosterSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** Format: uuid */
                        snapshotId: string;
                        deleted: boolean;
                    };
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRosterPlayerChain: {
        parameters: {
            query: {
                /** @description Tacticus user ID of the guild member. */
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PlayerRosterChainResponse'];
                };
            };
            400: components['responses']['ApiError'];
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    postGuildRosterMigrate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migration result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @description Number of snapshots whose data was migrated into the new tables. */
                        migrated: number;
                        /** @description Number of snapshots already present in GuildSnapshotPlayerIndex (idempotency — not re-processed). */
                        skipped: number;
                    };
                };
            };
            401: components['responses']['Unauthorized'];
            502: components['responses']['TacticusApiError'];
        };
    };
    GetGuildPerformanceIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildPerformanceIndexResponse'];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
            /** @description Forbidden — guild has not enabled member performance sharing. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
            /** @description Tacticus API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
        };
    };
    getSharedLeaderboards: {
        parameters: {
            query?: {
                /** @description Season number; omit for current season (live data) */
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined leaderboards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SharedLeaderboardsResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getMemberGuildPerformanceIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildPerformanceIndexResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getMemberGuildRaidCurrentSeason: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anonymized current-season summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HistoricalSeasonResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getMemberGuildRaidSeason: {
        parameters: {
            query?: {
                /** @description Unix epoch milliseconds. Any persisted row aggregated before this timestamp is re-fetched. */
                forceRefreshAfter?: number;
            };
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anonymized season summary (always GuildSeasonSummary shape; non-self playerIds are 'Anonymous') */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HistoricalSeasonResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    updateTacticusApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['SetTacticusApiKeyRequest'];
            };
        };
        responses: {
            /** @description OK — keys saved, player data returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @description Raw player response from the Tacticus API */
                        player?: {
                            [key: string]: unknown;
                        };
                        combinedGuildTags?: string[] | null;
                        okString?: string;
                    };
                };
            };
            /** @description No content — apiKey was empty, keys cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components['responses']['TacticusApiError'];
            401: components['responses']['Unauthorized'];
        };
    };
    getMemberSharedLeaderboards: {
        parameters: {
            query?: {
                /** @description Season number; omit for current season */
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combined leaderboards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SharedLeaderboardsResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildTokenUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildTokenUsageResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getMemberGuildTokenUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildTokenUsageResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            403: components['responses']['ApiError'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
}
