/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/guild/raid/seasons': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all known seasons for this guild with their aggregation status. Seasons in the 11-season window that have not yet been fetched appear as NotAggregated. Old seasons only appear if already persisted. */
        get: operations['getGuildRaidSeasons'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/raid/{season}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current season's raw Tacticus API response, or a persisted aggregated summary for a historical season. */
        get: operations['getGuildRaidSeason'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/snapshots': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists roster snapshot metadata (no member data). Includes atCapacity flag so the frontend can disable the add-snapshot button. */
        get: operations['getGuildRosterSnapshots'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/roster/snapshot/{snapshotId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a single roster snapshot with its full member list, filtered to current guild members. */
        get: operations['getGuildRosterSnapshot'];
        put?: never;
        post?: never;
        /** Deletes a roster snapshot by its ID. */
        delete: operations['deleteGuildRosterSnapshot'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/guild/raid/performance-index': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns per-player performance-index scalars for every aggregated historical season. */
        get: operations['GetGuildPerformanceIndex'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GuildApiError: {
            code: string;
            message: string;
            data?: unknown;
        };
        /**
         * @description 0=Found, 1=NotFound, 2=Empty, 3=TransientError, 4=TooOld (out of 11-season window and not in DB), 5=NotAggregated (in window but not yet fetched)
         * @enum {integer}
         */
        SeasonFetchStatus: 0 | 1 | 2 | 3 | 4 | 5;
        GuildRaidSeasonsResponse: {
            currentSeason?: number | null;
            guildTag: string;
            seasons: components['schemas']['GuildSeasonEntry'][];
        };
        GuildSeasonEntry: {
            season: number;
            status: components['schemas']['SeasonFetchStatus'];
            /** Format: date-time */
            aggregatedAt?: string | null;
        };
        /** @description Returned when the requested season equals the current season. Contains the raw Tacticus API payload. */
        CurrentSeasonRaidResponse: {
            season: number;
            raidResponse: {
                [key: string]: unknown;
            };
        };
        /** @description Returned for a historical season that has been aggregated and persisted. */
        HistoricalSeasonResponse: {
            season: number;
            status: components['schemas']['SeasonFetchStatus'];
            summary?: components['schemas']['GuildSeasonSummary'];
            /** Format: date-time */
            aggregatedAt?: string;
        };
        EnemyInfo: {
            enemyId: string;
            rarity: string;
            /** @description 0=boss, 1=left prime, 2=right prime */
            encounterIndex: number;
            maxHp: number;
            set: number;
        };
        GuildSeasonSummary: {
            version: number;
            season: number;
            /**
             * Format: int64
             * @description Total damage across all rarities, tokens and bombs
             */
            totalDamage: number;
            damageSummary: components['schemas']['GuildDamageSeasonSummary'];
            /** @description Top-5 single hits per boss/prime, top-2 rarities only */
            leaderboards: components['schemas']['GuildSeasonBossLeaderboard'][];
            /** @description Per-loop per-boss token counts, all rarities */
            loops: components['schemas']['GuildSeasonLoopInfo'][];
            /** @description Per-player hit-vs-guild ratios, top-2 rarities, bosses only */
            performanceIndex: components['schemas']['GuildSeasonPerformanceIndexEntry'][];
            /** @description Raw per-player hit arrays plus guild aggregates, top-2 rarities */
            bossPerformance: components['schemas']['GuildSeasonBossPerformanceEntry'][];
        };
        GuildDamageSeasonSummary: {
            textData: components['schemas']['GuildDamageSeasonSummaryTextData'];
            guildEntries: components['schemas']['GuildDamageSeasonSummaryGuildBossEntry'][];
            playerEntries: components['schemas']['GuildDamageSeasonSummaryPlayerBossEntry'][];
        };
        GuildDamageSeasonSummaryTextData: {
            playerData: components['schemas']['GuildDamageSeasonSummaryTextPlayerData'][];
        };
        GuildDamageSeasonSummaryTextPlayerData: {
            /** @description Null when anonymized */
            playerId?: string | null;
            tokens: number;
            bombs: number;
            primeHits: number;
            bossKillHits: number;
            /** Format: int64 */
            maxDamage: number;
            /** Format: int64 */
            totalDamage: number;
            maxDamageTarget?: components['schemas']['EnemyInfo'];
        };
        GuildDamageSeasonSummaryGuildBossEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            /** Format: double */
            averageDamage: number;
            /** Format: double */
            averageDamageWithoutKills: number;
            /** Format: int64 */
            maxDamage: number;
            /** Format: int64 */
            maxDamageWithoutKills?: number | null;
            maxDamagePlayerId?: string | null;
            maxDamageWithoutKillsPlayerId?: string | null;
            maxDamageComp?: string[] | null;
            maxDamageWithoutKillsComp?: string[] | null;
        };
        GuildDamageSeasonSummaryPlayerBossEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            /** @description Null when anonymized */
            playerId?: string | null;
            /** Format: double */
            averageDamage: number;
            /** Format: double */
            averageDamageWithoutKills: number;
            /** Format: int64 */
            maxDamage: number;
            /** Format: int64 */
            maxDamageWithoutKills?: number | null;
            maxDamageComp?: string[] | null;
            maxDamageWithoutKillsComp?: string[] | null;
        };
        GuildSeasonBossLeaderboard: {
            enemyInfo: components['schemas']['EnemyInfo'];
            entries: components['schemas']['GuildSeasonBossLeaderboardEntry'][];
        };
        GuildSeasonBossLeaderboardEntry: {
            /** Format: int64 */
            damage: number;
            guildTag?: string | null;
            isOwnGuild?: boolean | null;
            /** @description Null when anonymized */
            playerId?: string | null;
            /** @description Null when anonymized */
            comp?: string[] | null;
        };
        GuildSeasonLoopInfo: {
            loopNumber: number;
            enemyInfo: components['schemas']['EnemyInfo'];
            bossTokens: number;
            leftPrimeTokens: number;
            rightPrimeTokens: number;
        };
        GuildSeasonPerformanceIndexEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            playerEntries: components['schemas']['GuildSeasonPerformanceIndexPlayerEntry'][];
        };
        GuildSeasonPerformanceIndexPlayerEntry: {
            /** @description Null when anonymized */
            playerId?: string | null;
            /**
             * Format: double
             * @description Player avg / guild avg including kills. 1.5 = +50%.
             */
            performanceIndex: number;
            /** Format: double */
            performanceIndexWithoutKills: number;
        };
        GuildSeasonBossPerformanceEntry: {
            enemyInfo: components['schemas']['EnemyInfo'];
            /** Format: double */
            guildAverageDamage: number;
            /** Format: double */
            guildAverageDamageWithoutKills: number;
            /** Format: int64 */
            guildMaxDamage: number;
            /** Format: int64 */
            guildMaxDamageWithoutKills: number;
            playerEntries: components['schemas']['GuildSeasonPlayerPerformanceEntry'][];
        };
        GuildSeasonPlayerPerformanceEntry: {
            /** @description Null when anonymized */
            playerId?: string | null;
            nonKillHits: number[];
            killHits: number[];
        };
        GuildRosterSnapshotsResponse: {
            snapshots: components['schemas']['RosterSnapshotInfo'][];
            atCapacity: boolean;
            maxSnapshots: number;
        };
        RosterSnapshotInfo: {
            /** Format: uuid */
            snapshotId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        RosterSnapshotDetail: {
            /** Format: uuid */
            snapshotId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            members: components['schemas']['RosterSnapshotMember'][];
        };
        /** @description Core userId plus any extra properties stored via JsonExtensionData */
        RosterSnapshotMember: {
            userId: string;
        } & {
            [key: string]: unknown;
        };
        SeasonPlayerPerformanceIndex: {
            /** @description Null when the caller is a keyless member (only their own entry is returned). */
            playerId?: string | null;
            /**
             * Format: double
             * @description Player avg non-kill boss damage / guild avg. 1.5 = +50% above guild mean.
             */
            performanceIndex?: number;
        };
        SeasonPerformanceIndexData: {
            season?: number;
            playerEntries?: components['schemas']['SeasonPlayerPerformanceIndex'][];
        };
        GuildPerformanceIndexResponse: {
            guildTag?: string;
            /** @description One entry per season with stored performance-index data, newest first. */
            entries?: components['schemas']['SeasonPerformanceIndexData'][];
        };
    };
    responses: {
        /** @description Missing or invalid JWT */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['GuildApiError'];
            };
        };
        /** @description Not found, permission denied, or other application error */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['GuildApiError'];
            };
        };
        /** @description Upstream Tacticus API call failed */
        TacticusApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['GuildApiError'];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGuildRaidSeasons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildRaidSeasonsResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRaidSeason: {
        parameters: {
            query?: {
                /** @description Unix epoch milliseconds. Any persisted row with aggregatedAt before this timestamp is re-fetched and re-aggregated. */
                forceRefreshAfter?: number;
            };
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current-season raw response or historical aggregated summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json':
                        | components['schemas']['CurrentSeasonRaidResponse']
                        | components['schemas']['HistoricalSeasonResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRosterSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildRosterSnapshotsResponse'];
                };
            };
            401: components['responses']['Unauthorized'];
            502: components['responses']['TacticusApiError'];
        };
    };
    getGuildRosterSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['RosterSnapshotDetail'];
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    deleteGuildRosterSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** Format: uuid */
                        snapshotId: string;
                        deleted: boolean;
                    };
                };
            };
            401: components['responses']['Unauthorized'];
            404: components['responses']['ApiError'];
            502: components['responses']['TacticusApiError'];
        };
    };
    GetGuildPerformanceIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildPerformanceIndexResponse'];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
            /** @description Forbidden — guild has not enabled member performance sharing. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
            /** @description Tacticus API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuildApiError'];
                };
            };
        };
    };
}
